# .circleci/config.yml

version: 2.0
jobs:
  build:
    docker:
      - image: gableroux/unity3d:2020.1.0b9
    steps:
      - checkout
      - run:
          command: which git
      - run:
          command: git --version
