version: 2

aliases:
  - &run
    parallelism: 4
    steps:
      - checkout
      - run:
          command: chmod u+x ./run.sh && ./run.sh

jobs:
  job_1:
    docker:
      - image: unityci/editor:ubuntu-2021.2.7f1-base-0.15.0
    <<: *run

workflows:
  version: 2
  build:
    jobs:
      - job_1