# .circleci/config.yml

version: 2.0
jobs:
  build:
    docker:
      - image: gableroux/unity3d:2018.4.21f1-android
    steps:
      - checkout
      - run:
          command: java -version
      - run:
          command: sdkmanager --version
      - run:
          command: sdkmanager --list
