# .circleci/config.yml

version: 2.0
jobs:
  build:
    docker:
      - image: gableroux/unity3d:2018.4.21f1-android
    steps:
      - checkout
      - run:
          command: java -version
      - run:
          command: /opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/tools/bin/sdkmanager --version
      - run:
          command: /opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/tools/bin/sdkmanager --list
