# .circleci/config.yml

version: 2.0
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run:
          command: |
            wget https://raw.githubusercontent.com/Unity-CI/docker-linux/master/Dockerfile
            docker build . -t unity-ci/docker-linux

